"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GUI.py']
DATA_FILES = ['setting.json', 'content_fix.py', 'downloader.py', 'initialize.py']
OPTIONS = {
    'argv_emulation': True,
    'packages': ['flask', 'flask_bootstrap', 'flask_wtf', 'flask_script', 'lxml', 'requests', 'jinja2'],
    'resources': ['./templates', './static', './opencc']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
